name: push-ci
on: push

jobs:
  npm-run-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: npm install
      - run: echo '{}' > local.json
      - run: npm run ci
